version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $DOCKERHUB_USERNAME
      - echo $DOCKERHUB_PASS
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS      
  build:
    commands:
      - echo Restoring dependencies...     
      - echo Building the application...     
      - echo Publishing the application...    
      - echo Building the Docker image...     
      - docker build -t $IMAGE_URI:latest .
      - echo Tagging image with tag "$IMAGE_TAG"...
      - docker tag $IMAGE_URI:latest $IMAGE_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $IMAGE_URI:$IMAGE_TAG

artifacts:
  files: imagedefinitions.json
